name: ethnopedia
services:
  frontend:
    container_name: ethnopedia-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://music-put.lab.dariah.pl/ethnopedia-api/
    ports:
      - "4050:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
  backend:
    container_name: ethnopedia-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4051:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # anonymous volume for node_modules only
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://ethnopedia-mongodb:27017
    restart: always
  mongodb:
    container_name: ethnopedia-mongodb
    ports:
      - "27017:27017"
    # image: mongodb/mongodb-community-server:latest # use this one instead on proper processor architecture
    image: bitnami/mongodb:4.4.5  # fix for Xeon processor missing AVX instruction set https://www.mongodb.com/docs/manual/tutorial/install-mongodb-community-with-docker/
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGO_NETWORK_MESSAGE_TIMEOUT_MS: 10000
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mongodb_data:/bitnami/mongodb
      # - mongodb_data:/data/db # for image mongodb/mongodb-community-server:latest
    restart: always

volumes:
  mongodb_data: